### PR TITLE
Gary

### PR DESCRIPTION
**Pull request by Neverfeeel**
What do you think memberProfile.jsp

### CODE REVIEW

**Comment by Neverfeeel** [comment]
WhatsApp Image 2020-01-02 at 4 01 37 PM

**Comment by leileijng** [comment]
Can you screenshot more below? Security Question part?

**Comment by Neverfeeel** [comment]
web
Here you go

**Comment by leileijng** [comment]
It seems something wrong with set security question, you may need to edit that part again, thanks!

**Comment by Neverfeeel** [comment]
Alight!~~!

**Comment by Neverfeeel** [comment]
WhatsApp Image 2020-01-02 at 4 01 37 PM
Updated one

**Comment by leileijng** [comment]
Yes, looks fine. Can Merge.

**Comment by ZiYun1** [comment]
ok can merge

**Pull request merged**
